export const FETCH_LIST_COLLECTION_REQUEST = 'FETCH_LIST_COLLECTION_REQUEST';
export const FETCH_LIST_COLLECTION_SUCCESS = 'FETCH_LIST_COLLECTION_SUCCESS';
export const FETCH_LIST_COLLECTION_ERROR = 'FETCH_LIST_COLLECTION_ERROR';
export const CREATE_LIST_REQUEST = 'ADD_LIST_REQUEST';
export const CREATE_LIST_SUCCESS = 'ADD_LIST_SUCCESS';
export const CREATE_LIST_ERROR = 'ADD_LIST_ERROR';
export const EDIT_LIST_REQUEST = 'EDIT_LIST_REQUEST';
export const EDIT_LIST_SUCCESS = 'EDIT_LIST_SUCCESS';
export const EDIT_LIST_ERROR = 'EDIT_LIST_ERROR';

export const FETCH_ITEMS_FOR_LIST_REQUEST = 'FETCH_ITEMS_FOR_LIST_REQUEST';
export const FETCH_ITEMS_FOR_LIST_SUCCESS = 'FETCH_ITEMS_FOR_LIST_SUCCESS';
export const FETCH_ITEMS_FOR_LIST_ERROR = 'FETCH_ITEMS_FOR_LIST_ERROR';
export const GET_ITEM_TEMPLATE_REQUEST = 'GET_ITEM_TEMPLATE_REQUEST';
export const GET_ITEM_TEMPLATE_SUCCESS = 'GET_ITEM_TEMPLATE_SUCCESS';
export const GET_ITEM_TEMPLATE_ERROR = 'GET_ITEM_TEMPLATE_ERROR';
export const SAVE_ITEM_REQUEST = 'SAVE_ITEM_REQUEST';
export const SAVE_ITEM_SUCCESS = 'SAVE_ITEM_SUCCESS';
export const SAVE_ITEM_ERROR = 'SAVE_ITEM_ERROR';
export const BUY_ITEM_REQUEST = 'BUY_ITEM_REQUEST';
export const BUY_ITEM_SUCCESS = 'BUY_ITEM_SUCCESS';
export const BUY_ITEM_ERROR = 'BUY_ITEM_ERROR';
export const RETURN_ITEM_REQUEST = 'RETURN_ITEM_REQUEST';
export const RETURN_ITEM_SUCCESS = 'RETURN_ITEM_SUCCESS';
export const RETURN_ITEM_ERROR = 'RETURN_ITEM_ERROR';

export const FETCH_PRODUCT_COLLECTION_REQUEST = 'FETCH_PRODUCT_COLLECTION_REQUEST';
export const FETCH_PRODUCT_COLLECTION_SUCCESS = 'FETCH_PRODUCT_COLLECTION_SUCCESS';
export const FETCH_PRODUCT_COLLECTION_ERROR = 'FETCH_PRODUCT_COLLECTION_ERROR';
export const SEARCH_PRODUCT_REQUEST = 'SEARCH_PRODUCT_REQUEST';
export const SEARCH_PRODUCT_SUCCESS = 'SEARCH_PRODUCT_SUCCESS';
export const SEARCH_PRODUCT_ERROR = 'SEARCH_PRODUCT_ERROR';
export const CREATE_PRODUCT_REQUEST = 'CREATE_PRODUCT_REQUEST';
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS';
export const CREATE_PRODUCT_ERROR = 'CREATE_PRODUCT_ERROR';

export const FETCH_GROUP_COLLECTION_REQUEST = 'FETCH_GROUP_COLLECTION_REQUEST';
export const FETCH_GROUP_COLLECTION_SUCCESS = 'FETCH_GROUP_COLLECTION_SUCCESS';
export const FETCH_GROUP_COLLECTION_ERROR = 'FETCH_GROUP_COLLECTION_ERROR';
export const CREATE_GROUP_REQUEST = 'CREATE_GROUP_REQUEST';
export const CREATE_GROUP_SUCCESS = 'CREATE_GROUP_SUCCESS';
export const CREATE_GROUP_ERROR = 'CREATE_GROUP_ERROR';

export const FETCH_UNIT_COLLECTION_REQUEST = 'FETCH_UNIT_COLLECTION_REQUEST';
export const FETCH_UNIT_COLLECTION_SUCCESS = 'FETCH_UNIT_COLLECTION_SUCCESS';
export const FETCH_UNIT_COLLECTION_ERROR = 'FETCH_UNIT_COLLECTION_ERROR';

export const UI_SIDEBAR_SHOW = 'UI_SIDEBAR_SHOW';
export const UI_SIDEBAR_HIDE = 'UI_SIDEBAR_HIDE';
export const UI_SIDEBAR_TOGGLE = 'UI_SIDEBAR_TOGGLE';
export const UI_SIDEBAR_LIST_MANAGER_MODE = 'UI_SIDEBAR_LIST_MANAGER_MODE';
